# Based on http://docs.haskellstack.org/en/stable/travis_ci.html
# and http://docs.haskellstack.org/en/stable/GUIDE.html#travis-with-caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev
    - libcairo2
    - libcairo2-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
#env:
#- ARGS=""
#- ARGS="--resolver lts-2"
#- ARGS="--resolver lts-3"
#- ARGS="--resolver lts"
#- ARGS="--resolver nightly"

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# --no-terminal works around some quirks in Travis's terminal implementation.
script:
- stack $ARGS --no-terminal --install-ghc install alex happy
- stack $ARGS --no-terminal --install-ghc install gtk2hs-buildtools
- stack $ARGS --no-terminal --install-ghc build

notifications:
  email: true

