flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.0.0
- QuickCheck-2.8.1
- alex-3.1.6
- bytestring-lexing-0.4.3.3
- cairo-0.13.1.1
- colour-2.3.3
- gtk2hs-buildtools-0.13.0.5
- happy-1.19.5
- hashable-1.2.3.3
- hashtables-1.2.1.0
- mtl-2.2.1
- primitive-0.6.1.0
- random-1.1
- strptime-1.0.10
- text-1.2.2.0
- tf-random-0.5
- utf8-string-1.0.1.1
- vcs-revision-0.0.2
- vector-0.11.0.0
resolver: ghc-7.10.3
